//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PerzoneFalze.Database.Tables
{

    public partial class ListaContatti : XPLiteObject
    {
        int fPerzonaID;
        [Key]
        public int PerzonaID
        {
            get { return fPerzonaID; }
            set { SetPropertyValue<int>("PerzonaID", ref fPerzonaID, value); }
        }
        string fName;
        [Size(20)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fSurname;
        [Size(20)]
        public string Surname
        {
            get { return fSurname; }
            set { SetPropertyValue<string>("Surname", ref fSurname, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>("BirthDate", ref fBirthDate, value); }
        }
        DateTime fDateAdded;
        public DateTime DateAdded
        {
            get { return fDateAdded; }
            set { SetPropertyValue<DateTime>("DateAdded", ref fDateAdded, value); }
        }
        DateTime flastUpdate;
        public DateTime lastUpdate
        {
            get { return flastUpdate; }
            set { SetPropertyValue<DateTime>("lastUpdate", ref flastUpdate, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
        bool fStateOfMind;
        public bool StateOfMind
        {
            get { return fStateOfMind; }
            set { SetPropertyValue<bool>("StateOfMind", ref fStateOfMind, value); }
        }
    }

}
